### ISSUE TITLE
Error searching for movies that are within quotes from CSV

### ISSUE THREAD

**Issue by vgalbraith** [zedchance/oscars#15]
For example, searching for the movie titled: "Wanted, a Master" produces the following if quotes are not also entered:

![image](https://user-images.githubusercontent.com/37874205/99158815-dc1b0500-268b-11eb-83eb-48cda000d8ed.png)

Line 33 in FetchFromCSV checks for equality, I think it should check if the field contains the search query.

**Comment by vgalbraith** [comment]
![image](https://user-images.githubusercontent.com/37874205/99158968-41bbc100-268d-11eb-822f-92540de2d752.png)

**Comment by vgalbraith** [comment]
Interesting to note, the search does work from Visoth's unmerged data() code, so if we get to the point we can transition to that then we won't need to address this in FetchFromCSV.
![image](https://user-images.githubusercontent.com/37874205/99159992-2f468500-2697-11eb-9a82-09d973cc2615.png)

**Comment by zedchance** [comment]
So
```
http://localhost:8080/movie/wanted,%20a%20master
```
is working on the current master (https://github.com/zedchance/oscars/commit/ebccc0a7440bb8ee26839ebb9fc77e1e39483fa3). I'm not sure when it started working as I haven't tested it in a while.

**Comment by vgalbraith** [comment]
Your refactor (#26) did it, since the quotes are removed when the movies are put into memory, then we are just searching from memory.
