### ISSUE TITLE
Some of the award entries are picking up some extra quotes in their "name" field

### ISSUE THREAD

**Issue by vgalbraith** [zedchance/oscars#8]
![image](https://user-images.githubusercontent.com/37874205/98757220-e930af00-2380-11eb-9d31-ff99c78c30d1.png)

**Comment by zedchance** [comment]
I'm not sure these are added quotes, that line for the MAKEUP AND HAIRSTYLING for 1917 does have quotes in the name field:

https://github.com/zedchance/oscars/blob/d2d11697f08de3ce1487e738cc98d2178541a556/src/main/CSVFile/KaggleData_the_oscar_award.csv#L10333

**Comment by vgalbraith** [comment]
I see, I was looking at the file in excel and the quotes are omitted there. Do you think we should setup some sort of formatter to clear those or just leave them in?

**Comment by vgalbraith** [comment]
OK, I see its due to the nature of a list separated by commas, when they put multiple people in the field with commas they have to put it in quotes to avoid it breaking it up by those additional commas

**Comment by zedchance** [comment]
Oh yeah that makes sense. So I guess when we extract that name field we could probably strip them off the ends if they exist. This is what the Prof was talking about with having to clean our data.
